<a href="https://colab.research.google.com/github/2303A52085/23CSBTB39-40/blob/main/array1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
list1=[3,4,6,7]
list2=[6,3,26,7]
print(list1)
print(list2)
print(type(list1))
print(type(list2))

[3, 4, 6, 7]
[6, 3, 26, 7]
<class 'list'>
<class 'list'>


In [2]:
import numpy as np
array1=np.array(list1)
print(array1)
array2=np.array(list2)
print(array2)

[3 4 6 7]
[ 6  3 26  7]


In [3]:
print(array1+array2)

[ 9  7 32 14]


In [4]:
print(type(array1))
print(type(array2))


<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [11]:
print(list1+list2)
print(array1*array2)
print(array1-array2)


[3, 4, 6, 7, 6, 3, 26, 7]
[ 18  12 156  49]
[ -3   1 -20   0]
[0.5        1.33333333 0.23076923 1.        ]


In [12]:
division=array1/array2
print(division)

[0.5        1.33333333 0.23076923 1.        ]


In [17]:
addition=array1+array2
print(addition)

[ 9  7 32 14]


In [20]:
poweroff=array1**2
print(poweroff)
poweroff2=array2**3
print(poweroff2)

[ 9 16 36 49]
[  216    27 17576   343]


In [21]:
print("addtion of two arrays:",array1,"+",array2,"is",addition)

addtion of two arrays: [3 4 6 7] + [ 6  3 26  7] is [ 9  7 32 14]


In [24]:
sin = np.sin(array1)
print("sin result for",array1,":",sin)
sin2 = np.sin(array2)
print("sin result for",array2,":",sin2)
log=np.log(array1)
print("log result for",array1,":",log)
log2=np.log(array2)
print("log result for",array2,":",log2)
exp=np.exp(array1)
print("expainstion result for",array1,":",exp)
exp2=np.exp(array2)
print("expainstion result for",array2,":",exp2)

sin result for [3 4 6 7] : [ 0.14112001 -0.7568025  -0.2794155   0.6569866 ]
sin result for [ 6  3 26  7] : [-0.2794155   0.14112001  0.76255845  0.6569866 ]
log result for [3 4 6 7] : [1.09861229 1.38629436 1.79175947 1.94591015]
log result for [ 6  3 26  7] : [1.79175947 1.09861229 3.25809654 1.94591015]
expainstion result for [3 4 6 7] : [  20.08553692   54.59815003  403.42879349 1096.63315843]
expainstion result for [ 6  3 26  7] : [4.03428793e+02 2.00855369e+01 1.95729609e+11 1.09663316e+03]
